shared:
  image: node:16

annotations:
  screwdriver.cd/chainPR: true

jobs:
  test:
    requires: [~pr, ~commit]
    steps:
      - echo "test2"
  test2:
    requires: [test]
    steps:
      - echo "test"
  test3:
    requires: [~pr]
    steps:
      - echo "test"
  test4:
    requires: [~commit]
    steps:
      - echo "test"
